import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

export interface ExportData {
  patients?: any[];
  ivLines?: any[];
  reportData?: any;
  stats?: any;
  dateRange?: {
    start: string;
    end: string;
  };
  generatedAt?: string;
  generatedBy?: string;
}

export const exportToPDF = async (data: ExportData, title?: string) => {
  const doc = new jsPDF();
  const reportTitle = title || 'Hospital IV Management Report';
  
  // Header
  doc.setFontSize(20);
  doc.text(reportTitle, 20, 20);
  
  doc.setFontSize(12);
  if (data.dateRange) {
    doc.text(`Report Period: ${data.dateRange.start} to ${data.dateRange.end}`, 20, 30);
  }
  doc.text(`Generated: ${data.generatedAt || new Date().toLocaleString()}`, 20, 40);
  if (data.generatedBy) {
    doc.text(`Generated by: ${data.generatedBy}`, 20, 50);
  }
  
  // Summary Statistics
  doc.setFontSize(16);
  doc.text('Summary Statistics', 20, 70);
  
  const summaryData = [
    ['Total Patients', (data.patients?.length || data.stats?.totalPatients || 0).toString()],
    ['Total IV Lines', (data.ivLines?.length || data.stats?.activeIVLines || 0).toString()],
    ['Active IV Lines', (data.ivLines?.filter(line => line.status === 'active').length || data.stats?.activeIVLines || 0).toString()],
    ['Average Phlebitis Score', (data.reportData?.averagePhlebitisScore?.toFixed(1) || data.stats?.averagePhlebitisScore?.toFixed(1) || '0.0')],
    ['Success Rate', `${data.reportData?.successRate || data.stats?.successRate || 0}%`]
  ];
  
  autoTable(doc, {
    startY: 80,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] }
  });
  
  // IV Lines Details
  if (data.ivLines && data.ivLines.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.text('IV Lines Details', 20, 20);
    
    const ivLinesData = data.ivLines.map(line => [
      line.patient?.patient_id || line.patient_id || 'N/A',
      line.iv_type,
      line.insertion_site || 'N/A',
      line.insertion_date ? new Date(line.insertion_date).toLocaleDateString() : 'N/A',
      line.removal_date ? new Date(line.removal_date).toLocaleDateString() : 'Active',
      (line.phlebitis_score || 0).toString(),
      line.status
    ]);
    
    autoTable(doc, {
      startY: 30,
      head: [['Patient ID', 'Type', 'Site', 'Inserted', 'Removed', 'Phlebitis', 'Status']],
      body: ivLinesData,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] },
      styles: { fontSize: 8 }
    });
  }
  
  // Save the PDF
  doc.save(`${reportTitle.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const exportToExcel = async (data: ExportData, title?: string) => {
  const workbook = XLSX.utils.book_new();
  const reportTitle = title || 'Hospital IV Management Report';
  
  // Summary Sheet
  const summaryData = [
    ['Metric', 'Value'],
    ['Report Title', reportTitle],
    ['Report Period', data.dateRange ? `${data.dateRange.start} to ${data.dateRange.end}` : 'N/A'],
    ['Generated', data.generatedAt || new Date().toLocaleString()],
    ['Generated By', data.generatedBy || 'System'],
    [''],
    ['Total Patients', data.patients?.length || data.stats?.totalPatients || 0],
    ['Total IV Lines', data.ivLines?.length || data.stats?.activeIVLines || 0],
    ['Active IV Lines', data.ivLines?.filter(line => line.status === 'active').length || data.stats?.activeIVLines || 0],
    ['Average Phlebitis Score', data.reportData?.averagePhlebitisScore?.toFixed(1) || data.stats?.averagePhlebitisScore?.toFixed(1) || '0.0'],
    ['Success Rate (%)', data.reportData?.successRate || data.stats?.successRate || 0]
  ];
  
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');
  
  // Patients Sheet
  if (data.patients && data.patients.length > 0) {
    const patientsData = [
      ['Patient ID', 'Department', 'Status', 'Admission Date']
    ];
    
    data.patients.forEach(patient => {
      patientsData.push([
        patient.patient_id,
        patient.department?.name || patient.department || 'N/A',
        patient.status,
        patient.admission_date ? new Date(patient.admission_date).toLocaleDateString() : 
        patient.created_at ? new Date(patient.created_at).toLocaleDateString() : 'N/A'
      ]);
    });
    
    const patientsSheet = XLSX.utils.aoa_to_sheet(patientsData);
    XLSX.utils.book_append_sheet(workbook, patientsSheet, 'Patients');
  }
  
  // IV Lines Sheet
  if (data.ivLines && data.ivLines.length > 0) {
    const ivLinesData = [
      [
        'Patient ID', 'IV Type', 'Insertion Site', 'Insertion Date', 'Removal Date',
        'Cannulas Used', 'Syringes Used', 'Gloves Used', 'Saline (ml)',
        'Time Taken (min)', 'Phlebitis Score', 'Site Pain', 'Site Redness',
        'Site Swelling', 'Status', 'Notes'
      ]
    ];
    
    data.ivLines.forEach(line => {
      ivLinesData.push([
        line.patient?.patient_id || line.patient_id || 'N/A',
        line.iv_type,
        line.insertion_site || 'N/A',
        line.insertion_date ? new Date(line.insertion_date).toLocaleDateString() : 'N/A',
        line.removal_date ? new Date(line.removal_date).toLocaleDateString() : '',
        line.cannula_count || line.cannulas_used || 0,
        line.syringe_count || line.syringes_used || 0,
        line.glove_count || line.gloves_used || 0,
        line.normal_saline_ml || 0,
        line.time_taken_minutes || line.time_taken || 0,
        line.phlebitis_score || 0,
        line.site_pain !== undefined ? (line.site_pain ? 'Yes' : 'No') : 'N/A',
        line.site_redness ? 'Yes' : 'No',
        line.site_swelling ? 'Yes' : 'No',
        line.status,
        line.notes || ''
      ]);
    });
    
    const ivLinesSheet = XLSX.utils.aoa_to_sheet(ivLinesData);
    XLSX.utils.book_append_sheet(workbook, ivLinesSheet, 'IV Lines');
  }
  
  // Save the Excel file
  XLSX.writeFile(workbook, `${reportTitle.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`);
};